var $lists=$("#lists");
$(function(){function a(){$(".yao").removeClass("yao2");$(".yao").addClass("yao1");setTimeout(b,200)}function b(){$(".yao").removeClass("yao1");$(".yao").addClass("yao2");setTimeout(c,200)}function c(){$(".yao").removeClass("yao2");setTimeout(a,200)}$lists.imagesLoaded(function(){$lists.masonry({columnWidth:".grid-sizer",itemSelector:".item"})});window.optionchanged=!1;$("#userTab a").click(function(a){a.preventDefault();$(this).tab("show")});a();0<=reply_musicurl.length&&playbox.init("playbox");setTimeout(function(){$("#coverurl").animate({opacity:"0"},
1E3,"swing",function(){$(this).hide()})},5E3);list("")});function reloadlists(a,b){mytoggle($("#lists"),$("#page"));$("#page").hide();$("#page").css("opacity",0);$("#lists").css("opacity",1);$("#lists").show();$lists.masonry("remove",$lists.find(".item")).masonry();orderstr=0==a?orderstr0:orderstr1;$("#lists").attr("scrolltop",0);pageIndex=1;reload=!0;list(b)}
function mytoggle(a,b){hidetop=$(document).scrollTop();showtop=void 0===a.attr("scrolltop")?0:a.attr("scrolltop");b.animate({opacity:"0"},500,"swing",function(){b.hide();b.attr("scrolltop",hidetop);a.show();$("body,html").scrollTop(showtop);a.animate({opacity:"1"},100,"swing",function(){})})}
function displayit(a){reload=!0;for(i=0;100>i;i++)if(i==a){var b="menu_list"+a;"none"==document.getElementById(b).style.display?(document.getElementById(b).style.display="",reload=!1):document.getElementById(b).style.display="none"}else $("#menu_list"+i)&&$("#menu_list"+i).css("display","none")}
function closeall(){var a=document.getElementById("top_menu").getElementsByTagName("ul").length;for(i=0;i<a;i++)document.getElementById("top_menu").getElementsByTagName("ul").item(i).style.display="none";reload=!0}
function usersubmit(){$.ajax({url:index_url+"&usersubmit=1",data:{nickname:$("#nickname").val(),mobile:$("#mobile").val()},type:"post",dataType:"json",success:function(a){try{a.error?showMsg({msg:a.error}):(showMsg({msg:"\u4e2a\u4eba\u4fe1\u606f\u66f4\u65b0\u6210\u529f\uff01"}),closeall())}catch(b){showMsg({msg:"\u52a0\u8f7d\u5f02\u5e38\uff01"+b.message})}},error:function(a,b,c){showMsg({msg:"<label>"+JSON.stringify(a)+"</label><label>"+JSON.stringify(c)+"</label>"})}})}
var pageIndex=1,pageSize=reply_pagesize,orderstr=" createtime desc ",orderstr0=" createtime desc ",orderstr1=" sumcount desc ",isload=!0,reload=!0;GPC_pageid&&showpage(GPC_pageid);
function list(a){reload&&$("#lists").is(":visible")&&(reload=!1,$.ajax({url:index_url+"&showmore=1",data:{pageIndex:pageIndex,pageSize:pageSize,orderstr:orderstr,searchstr:a},type:"post",dataType:"json",success:function(b){try{if(b.error)showMsg({msg:b.error});else if(0==b.list.length||b.total<=(pageIndex+1)*pageSize&&(a=""))showMsg({msg:"\u5df2\u7ecf\u5168\u90e8\u52a0\u8f7d\uff01"});else{replycount(b.replycount);reload=!0;pageIndex+=1;var c="";$.each(b.list,function(a,b){c+=getHtml(b)});var c=c+
'<div class="item" style="min-width:200px;min-height:200px;"> <div class="tc-gridbox" style="min-width:200px;min-height:200px;text-align: center;"><iframe frameborder="no" scrolling="no" style="height: 200px;width: 200px;overflow:hidden;" src="http://www.msyou.cc/baiduhtml.html"></iframe></div></div>',d=$(c);$lists.append(d);d.imagesLoaded(function(){$lists.masonry("appended",d)})}}catch(f){showMsg({msg:"\u52a0\u8f7d\u5f02\u5e38\uff01"+f.message})}},error:function(a,c,d){showMsg({msg:"<label>"+JSON.stringify(a)+
"</label><label>"+JSON.stringify(d)+"</label>"})}}))}
function replycount(a){null!=a&&$("#replycount").html('\t\t\t\t\t\t<td style="width:24%;border-right: 1px solid #ddd;text-align:center;">'+(void 0===a.joincount?0:a.joincount)+'\t\t\t\t\t\t</td>\t\t\t\t\t\t<td style="width:24%;border-right: 1px solid #ddd;text-align:center;">'+(void 0===a.zancount?0:a.zancount)+'\t\t\t\t\t\t</td>\t\t\t\t\t\t<td style="width:24%;border-right: 1px solid #ddd;text-align:center;">'+(void 0===a.sharecount?0:a.sharecount)+'\t\t\t\t\t\t</td>\t\t\t\t\t\t<td style="width:24%;border-right: 1px solid #ddd;text-align:center;">'+
(void 0===a.viewcount?0:a.viewcount)+"\t\t\t\t\t\t</td>")}function listcount(a,b){null!=b&&($(".zan"+a).html(b.zancount),$(".share"+a).html(b.sharecount),$(".view"+a).html(b.sharecount))}
function showpage(a){reload=!1;$.ajax({url:index_url,data:{lid:a,showpage:1},type:"post",dataType:"json",success:function(a){if(a.error)showMsg({msg:a.error});else{replycount(a.replycount);upd_sharedata(a.p_share);e=a.list;content=JSON.parse(e.content);var c='<div class="header">                        <div>\t                        <div class="pull-left">\t                        \t<small>\u7f16\u53f7</small>\t\t                        <h3 style="font-size:18px;">'+e.bh+'</h3>\t                        </div>\t                        <div class="pull-right" id="minepm">\t\t                        <div class="pull-right" style="padding:0 5px 0 5px;">\t\t                        \t<small>\u6392\u540d</small>\t\t\t                        <h3 style="font-size:18px;">'+
e.pm+'</h3>\t\t                        </div>\t\t                        <div class="pull-right" style="padding:0 5px 0 5px;">\t\t                        \t<small>\u5f97\u5206</small>\t\t\t                        <h3 style="font-size:18px;">'+e.sumcount+'</h3>\t\t                        </div>\t                        </div>\t                        <div class="clearfix">\t                        \t<small>\u6635\u79f0</small>\t\t                        <h3 style="font-size:18px;">'+(void 0===e.nickname?
"\u6211\u53eb\u96f7\u950b":e.nickname)+'</h3>\t                        </div>                        </div>                        <hr>\t\t\t\t\t</div>\t\t\t\t\t<div class="body">'+content.content;$.each(content.imglists,function(a,b){b&&(c+='<div class="image" style="padding:5px;text-align: center;"><img  src="'+b+'" onerror="this.src=\''+reply_topurl+'\'" class="img-responsive"></div>')});c+='</div>                    <div class="footer">                    \t<div class="pull-left" style="padding:5px;">\t\t\t\t\t\t\t<i class="fa fa-thumbs-up yao" style="font-size:32px;color:#428bca;"></i><span class="zan'+
e.id+'" style="font-size:22px;color:#fff;line-height:40px;">'+e.zancount+'</span>\t\t\t\t\t\t</div>                        <div class="clearfix" onclick="dianzan('+e.id+');" style="background-color: rgba(72,64,60,0.8);color: #fff;text-align:center;">                        \t<h3 style="color:#fff;font-size:22px;line-height:28px">\u4e3a\u6211\u70b9\u8d5e</h3>                        </div>                    </div>\t\t\t\t\t<div class="footer">\t\t\t\t\t\t<div class="pull-left">\t\t\t\t\t\t\t<span class="meta">'+
e.createtime+'</span>\t\t\t\t\t\t</div>\t\t\t\t\t\t<div class="pull-right">\t\t\t\t\t\t\t<i class="fa fa-share-alt"></i><span class="count share'+e.id+'">'+e.sharecount+'</span>\t\t\t\t\t\t\t<i class="fa fa-eye"></i><span class="count view'+e.id+'">'+e.viewcount+'</span>\t\t\t\t\t\t</div>\t\t\t\t\t\t<div class="clearfix"></div>\t\t\t\t\t</div>\t\t\t\t</div>';$("#page>.tc-gridbox").html(c);mytoggle($("#page"),$("#lists"))}},error:function(a,c,d){showMsg({msg:"<label>"+JSON.stringify(a)+"</label><label>"+
JSON.stringify(d)+"</label>"})}})}
function getHtml(a){var b="";content=JSON.parse(a.content);return b='<div class="item" '+(0==reply_indexshowzan?'onclick="showpage('+a.id+')"':"")+'>\t\t\t\t\t\t<div class="tc-gridbox">\t                        <div class="header">\t\t\t\t\t\t\t\t<div class="item-image" '+(1==reply_indexshowzan?'onclick="showpage('+a.id+')"':"")+'>\t\t\t\t\t\t\t\t\t<img  src="'+a.imgurl+'" onerror="this.src=\''+reply_topurl+'\'" class="img-responsive" style="width:100%;">\t\t\t\t\t\t\t\t</div>'+(1==reply_indexshownick?
'                          <div>\t                        <div class="pull-left">\t                        \t<small>\u7f16\u53f7</small>\t\t                        <label style="font-size:18px;">'+a.bh+'</label>\t                        </div>\t                        <div class="pull-right" id="minepm">\t\t                        <div class="pull-right" style="padding:0 5px 0 5px;">\t\t                        \t<small>\u6392\u540d</small>\t\t\t                        <label style="font-size:18px;">'+
a.pm+'</label>\t\t                        </div>\t                        </div>\t                        <div class="clearfix">\t                        \t<small>\u6635\u79f0</small>\t\t                        <label>'+(void 0===a.nickname?"\u6211\u53eb\u96f7\u950b":a.nickname)+"</label>\t                        </div>                        </div>":"")+(1==reply_indexshowzan?'                        <div class="clearfix" onclick="dianzan('+a.id+');" style="background-color: rgba(72,64,60,0.8);color: #fff;text-align:center;">                        \t<h3 style="color:#fff;height: 30px;line-height: 30px;">\u4e3a\u6211\u70b9\u8d5e</h3>                        </div>':
"")+"\t                            <hr>\t                        </div>"+(1==reply_indexshowcontent?'\t                        <div class="body">\t                        \t'+content.content+"\t                        </div>":"")+'\t                        <div class="footer">\t                        \t<div class="pull-left"><span class="meta">'+a.createtime+'</span></div>\t                        \t<div class="pull-right">\t\t\t\t\t\t\t\t\t<i class="fa fa-thumbs-up"></i><span class="count zan'+
a.id+'">'+a.zancount+'</span>\t\t\t\t\t\t\t\t\t<i class="fa fa-share-alt"></i><span class="count share'+a.id+'">'+a.sharecount+'</span>\t\t                        \t<i class="fa fa-eye"></i><span class="count view'+a.id+'">'+a.viewcount+'</span>\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t<div class="clearfix"></div>\t\t\t\t\t\t\t</div>\t\t\t\t\t\t</div>                </div>'}
function dianzan(a){$.ajax({url:index_url,data:{lid:a,dianzan:1},type:"post",dataType:"json",success:function(a){try{a.error?showMsg({msg:a.error}):(replycount(a.replycount),listcount(a.listid,a.listcount),showMsg({msg:"\u70b9\u8d5e \u6210\u529f\uff01"}))}catch(c){showMsg({msg:"\u52a0\u8f7d\u5f02\u5e38\uff01"+c.message})}},error:function(a,c,d){showMsg({msg:"<label>"+JSON.stringify(a)+"</label><label>"+JSON.stringify(d)+"</label>"})}})}
$(function(){$(window).scroll(function(){parseFloat($(window).height())+parseFloat($(window).scrollTop())>=$(document.body).height()&&setTimeout(list(""),200)})});